remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: QSL Card Generator
description: by LU2EXV
logo: https://raw.githubusercontent.com/igonzalezb/QSL-Card-Generator/refs/heads/main/icon.svg
show_downloads: true
image: https://raw.githubusercontent.com/igonzalezb/QSL-Card-Generator/refs/heads/main/icon.svg
